apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cluster-role.yaml
  - cluster-role-binding.yaml
  - config-map-ldap-ca-cert.yaml
  - config-map.yaml
  - cronjob.yaml
  - service-account.yaml
